# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: pgPerf
  password: pgPerf
  host: localhost

development:
  <<: *default
  database: dbPerf

test:
  <<: *default
  database: your_app_name_test

production:
  <<: *default
  database: your_app_name_production
